apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-cooker-model-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  tls:
    - hosts:
        - user-rayaberova.lab.sspcloud.fr
  rules:
    - host: user-rayaberova.lab.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: team-cooker-model-service
                port:
                  number: 8000